### PR TITLE
op-mode: T4038: Remove legacy `vyatta-image-tools.pl`

### PR DESCRIPTION
**Pull request by erkin**
In addition, this fixes some bugs I found in `vyatta-op` completion system that were causing problems with the new implementation.
See vyos/vyos-1x#2507.

### CODE REVIEW

**Review by jestabro — CHANGES_REQUESTED** [review]
Note that one needs to remove reference to `vyatta-image-tools.pl` in `Makefile.am`

**Comment by jestabro** [comment]
Details in comment:
https://github.com/vyos/vyos-1x/pull/2507#issuecomment-1858687241

Exclude file.py from paging:
```
diff --git a/functions/interpreter/vyatta-op-run b/functions/interpreter/vyatta-op-run
index ee4cb1c..3260781 100644
--- a/functions/interpreter/vyatta-op-run
+++ b/functions/interpreter/vyatta-op-run
@@ -218,7 +218,7 @@ _vyatta_op_run ()
     local run_cmd=$(_vyatta_op_get_node_def_field $tpath/node.def run)
     run_cmd=$(_vyatta_op_conv_run_cmd "$run_cmd") # convert the positional parameters
     local ret=0
-    local cmd_regex="^(LESSOPEN=|less|pager|tail|/opt/vyatta/bin/vyatta-tshark-interface-port.pl).*"
+    local cmd_regex="^(.*/file.py.*|LESSOPEN=|less|pager|tail|/opt/vyatta/bin/vyatta-tshark-interface-port.pl).*"
     if [ -n "$run_cmd" ]; then
       eval $restore_shopts
       if [[ -t 1 &&  "${args[1]}" == "show" && ! $run_cmd =~ $cmd_regex ]] ; then
```

**Comment by jestabro** [comment]
The fix above does not quite work, as the `run_cmd` is, for comparison with the regex:
`sudo ${vyos_op_scripts_dir}/file.py`
without interpretation. I have yet to improve on the overkill in the patch above, but either that or a smarter pattern is needed.

**Comment by jestabro** [comment]
The following should work:
```
diff --git a/functions/interpreter/vyatta-op-run b/functions/interpreter/vyatta-op-run
index 7d67231..6bf6645 100644
--- a/functions/interpreter/vyatta-op-run
+++ b/functions/interpreter/vyatta-op-run
@@ -219,7 +219,8 @@ _vyatta_op_run ()
     run_cmd=$(_vyatta_op_conv_run_cmd "$run_cmd") # convert the positional parameters
     local ret=0
     # Exception for the `show file` command
-    local cmd_regex="^(LESSOPEN=|less|pager|tail|(sudo )?/usr/libexec/vyos/op_mode/file.py).*"
+    local file_cmd='\$\{vyos_op_scripts_dir\}\/file\.py'
+    local cmd_regex="^(LESSOPEN=|less|pager|tail|(sudo )?$file_cmd).*"
     if [ -n "$run_cmd" ]; then
       eval $restore_shopts
       if [[ -t 1 &&  "${args[1]}" == "show" && ! $run_cmd =~ $cmd_regex ]] ; then
```

**Review by jestabro — APPROVED** [review]

**Review by dmbaturin — APPROVED** [review]

**Pull request merged**
